// const swap = web3.eth.abi.encodeFunctionCall(
//     {
//       name: 'swap',
//       type: 'function',
//       inputs: [
//         { name: 'fromToken', type: 'address' },
//         { name: 'toToken', type: 'address' },
//         { name: 'fromAmount', type: 'uint256' },
//         { name: 'toAmount', type: 'uint256' },
//         { name: 'expectedAmount', type: 'uint256' },
//         { name: 'callees', type: 'address[]' },
//         { name: 'exchangeData', type: 'bytes' },
//         { name: 'startIndexes', type: 'uint256[]' },
//         { name: 'values', type: 'uint256[]' },
//         { name: 'beneficiary', type: 'address' },
//         { name: 'referrer', type: 'string' },
//         { name: 'useReduxToken', type: 'bool' },
//       ],
//     },
//     [
//       Token.MATIC,
//       Token.DAI,
//       sellTokenAmount,
//       minBuyAmount,
//       buyTokenAmount,
//       ['0x0'],
//       'bytes',
//       [0, 196],
//       [toWei('0.01', Unit.ETHER)],
//       '0x0',
//       'instadapp.io',
//       false,
//     ]
//   )
// const simpleSwap = web3.eth.abi.encodeFunctionCall(
//     {
//       name: 'simpleSwap',
//       type: 'function',
//       inputs: [
//         { name: 'fromToken', type: 'address' },
//         { name: 'toToken', type: 'address' },
//         { name: 'fromAmount', type: 'uint256' },
//         { name: 'toAmount', type: 'uint256' },
//         { name: 'expectedAmount', type: 'uint256' },
//         { name: 'callees', type: 'address[]' },
//         { name: 'exchangeData', type: 'bytes' },
//         { name: 'startIndexes', type: 'uint256[]' },
//         { name: 'values', type: 'uint256[]' },
//         { name: 'beneficiary', type: 'address' },
//         { name: 'referrer', type: 'string' },
//         { name: 'useReduxToken', type: 'bool' },
//       ],
//     },
//     [
//       Token.MATIC,
//       Token.DAI,
//       sellTokenAmount,
//       minBuyAmount,
//       buyTokenAmount,
//       ['0x0'],
//       'bytes',
//       [0, 196],
//       [toWei('0.01', Unit.ETHER)],
//       '0x0',
//       'instadapp.io',
//       false,
//     ]
//   )
